language: rust

branches:
  except:
    - gh-pages

rust:
- stable
- nightly

os:
- linux
- windows

script:
- cargo build --all
- cargo test --all

matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
