language: rust

rust:
- stable
- beta
- nightly

os:
- linux
- osx
- windows

script:
- cargo build --verbose --all
- cargo test --all

matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
