[book]
authors = ["Harald Hoyer"]
multilingual = false
src = "booksrc"
title = "chainerror"
description = "A tutorial for the chainerror rust crate."

[build]
build-dir = "book"
create-missing = false
