[package]
name = "chainerror"
version = "0.2.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/chainerror"
homepage = "https://haraldh.github.io/chainerror/"
repository = "https://github.com/haraldh/chainerror"
description = "Make chaining errors easy."
keywords = ["error"]
categories = ["rust-patterns"]
readme = "README.md"
exclude = [ "booksrc/*", "book.toml", "theme/*" ]

[features]
default = [ ]
no-fileline = []
display-cause = []
no-debug-cause = []
